# based on https://github.com/ArthurSonzogni/FTXUI

name: ci
on:
  create:
    tags:
    - v*
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop
      - master

jobs:
  test:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux GCC
          os: ubuntu-latest
          compiler: gcc
          gcov_executable: gcov

        - name: Linux Clang
          os: ubuntu-latest
          compiler: llvm
          gcov_executable: "llvm-cov gcov"

        - name: Macos Clang
          os: macos-latest
          compiler: llvm
          gcov_executable: "llvm-cov gcov"

        - name: Windows MSVC
          os: windows-latest
          compiler: cl

    runs-on: ${{ matrix.os }}
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Setup tooling"
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        vcvarsall: ${{ contains(matrix.os, 'windows') }} # should figure something else out for clang on windows
        cmake: true
        ninja: true
        clangtidy: true
        gcovr: "5.0"
        opencppcoverage: true

    # coverage should only be done with -O0, so don't include release builds
    - name: "Configure CMake"
      run: >
        cmake -S .
